apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: my-application
spec:
  groups:
    - name: Group1
      title: Text Field One
      description: Parameter capture for Group One
      items: 
        - name: Group1Text
          title: Example Text Field Capture One
          type: text
          default: default value
    - name: Group2
      title: Text Field Two
      description: Parameter capture for Group Two
      items:
        - name: Group2Text
          title: Example Text Field Capture Two
          type: text
          default: default value 2
          reccomended: true
    - name: certs
      title: Certs
      items: 
        - name: tls_private_key_file
          title: Private Key
          type: file
          recommended: true
        - name: tls_certificate_file
          title: Certificate
          type: file
          recommended: true